//
// Created by Noe on 30/06/24.
//

#ifndef PROYECTOC_TAREACURSOSMATRIZDISPERSA_H
#define PROYECTOC_TAREACURSOSMATRIZDISPERSA_H


class tareaCursosMatrizDispersa {

};


#endif //PROYECTOC_TAREACURSOSMATRIZDISPERSA_H
